- name: ansible command module
  hosts:  local
  tasks:
    - name: check user exists or not using command module 
      ansible.builtin.command:
      cmd:  id expense
      register: user
    - name: print the user info
      ansible.builtin.debug:
        msg:  "user information:{{user}}"