- name: default value
  hosts:  local
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg:  "Hello, {{course | default('terraform')}}"

- name: uppercase
  hosts:  local 
  tasks:
    - name: convert lower to uppercase
      vars:
        greetings: "Hello, Prathyusha"  
      ansible.builtin.debug:
        msg:  "{{greetings|upper}}"

- name: lowercase
  hosts:  local
  vars:
    course: DEVOPS
    trainer:  PRATHYU
    duration: 120HRS
  tasks:
    - name: upper to lower
      ansible.builtin.debug:
        msg:  "Hello,I have been learning {{course|lower}},from trainer {{trainer|lower}} for {{duration|lower}}"

- name: duplicates
  hosts:  local
  vars:
    course: ["shellscripting", "ansible", "devops", "devops", "ansible", "terraform", "linux", "linux"]
  tasks:
    - name:  remove duplicates
      ansible.builtin.debug:
        msg: "courses to take:{{course|unique}}"

- name: min and max
  hosts:  local
  tasks:
    - name: print min and max numbers
      vars:
        numbers:  [102, 100, 22323, 12133, 23133, 0223]
      ansible.builtin.debug:
        msg:  "min number:{{numbers|min}},max number:{{numbers|max}}"

- name: duplicates in numbers
  hosts: local
  vars:
    numbers:  [73, 23, 89, 23, 56, 73, 34, 45]
  tasks:
    - name: remove duplicates
      ansible.builtin.debug:
        msg:  "min:{{numbers|min}},max:{{numbers|max}}"

- name: dictionary to items/list
  hosts:  local
  vars:
    dictionary:
      course: devops
      student:  prathyushs
      age:  30
      country:  India
  tasks:
    - name: diction to items/list
      ansible.builtin.debug:
        msg:  "before convert:{{dictionary}}"
    - name: after convert
      ansible.builtin.debug:
        msg:  "after convert:{{dictionary|dict2items}}"
- name: items/list to dictionary
  hosts:  local
  vars:
    fruits:
      - fruit:  apple
        color:  red
      - fruit:  orange
        color:  orange
      - fruit:  mango
        color:  yellow
      - fruit:  banana
        color:  yellow
  tasks:
    - name: before convert
      ansible.builtin.debug:
        msg:  "before convert:{{fruits}}"
    - name: after convert
      ansible.builtin.debug:
        msg:  "after convert:{{fruits|items2dict(key_name='fruit',value_name='color')}}"  
- name: items/list to dictionary
  hosts:  local
  vars:
    list:
      - key:  apple
        value:  red
      - key:  orange
        value:  orange
      - key:  grapes
        value:  red
  tasks:
    - name: before convert
      ansible.builtin.debug:
        msg:  "before convert:{{list}}"
    - name: after convert
      ansible.builtin.debug:
        msg:  "after convert:{{list|items2dict}}"
              



  
      