- name: default value
  hosts:  local
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg:  "Hello, {{course | default('terraform')}}"

- name: uppercase
  hosts:  local 
  tasks:
    - name: convert lower to uppercase
      vars:
        greetings: "Hello, Prathyusha"  
      ansible.builtin.debug:
        msg:  "{{greetings|upper}}"

- name: lowercase
  hosts:  local
  vars:
    course: DEVOPS
    trainer:  PRATHYU
    duration: 120HRS
  tasks:
    - name: upper to lower
      ansible.builtin.debug:
        msg:  "Hello,I have been learning {{course|lower}},from trainer {{trainer|lower}} for {{duration|lower}}"

- name: duplicates
  hosts:  local
  vars:
    course: ["shellscripting", "ansible", "devops", "devops", "ansible", "terraform", "linux", "linux"]
  tasks:
    - name:  remove duplicates
      ansible.builtin.debug:
        msg: "courses to take:{{course|unique}}"

- name: min and max
  hosts:  local
  tasks:
    - name: print min and max numbers
      vars:
        numbers:  [102, 100, 22323, 12133, 23133, 0223]
      ansible.builtin.debug:
        msg:  "min number:{{numbers|min}},max number:{{numbers|max}}"

  
      