- name: conditions in ansible
  hosts: local
  become: yes
  tasks:
    - name: command module in ansible
      ansible.builtin.command:  id expense
      register: user
      ignore_errors:  true
    - name: display user info
      ansible.builtin.debug:
        msg:  "user info is:{{user}}"
    - name: condition usage
      ansible.builtin.command:  useradd expense
      when: user.rc!=0