- name: install and remove packages
  hosts: local
  become: yes
  tasks:
    - name: install and remove packages
      ansible.builtin.dnf:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - name: mysql
          state:  present
        - name: nginx
          state:  absent
        - name: postfix
          state:  absent