- name: variable preference
  hosts:  local
  vars_files:
    - vars.yaml
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg:  "Hello,I have been learning {{course}} from {{trainer}} for {{duration}}"
  
